#' Function to summaryze the diagnosis information
#'
#' Given the data generated by \code{phewasData} R function, generates
#' a \code{data.frame} with one diagnosis code per row and the corresponding number of patients per age group, and sex, and 
#' with the potential of getting a more detailed count aggregating also by race, and severity status.
#'
#' @param input The data.frame with the sex phewas analysis. Output generated when running the \code{phewasData} R function.
#' @param diagnosisTime By default \code{'ALL'}.Change it to "beforeAdmission", "afterAdmission" according to your preferences. 
#' @param by.age_group By default FALSE. Set it to TRUE if you do want to aggregate the counts based on the age_group.
#' @param by.race By default FALSE. Set it to TRUE if you want to aggregate the counts based on race.
#' @param by.severe By default FALSE. Set it to TRUE if you want to aggregate the counts based on severity
#' @param obfuscation By default FALSE. If your IRB require obfuscation, change it to the minimum patient count allowed.
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get detailed information.
#' @return An object of class \code{data.frame} with the counts.
#' @examples
#'
#' diagnosisCount <- diagnosisSummary(
#'               input         = phewasDaata, 
#'               by.age_group  = TRUE,
#'               by.race       = FALSE,
#'               by.severe     = FALSE, 
#'               obfuscation   = FALSE
#'              )
#' @export diagnosisSummary

diagnosisSummary <- function( input, diagnosisTime = "ALL", by.age_group = FALSE, by.race = FALSE, by.severe = FALSE, plot = FALSE, obfuscation = FALSE, verbose = FALSE ){
  
  if( verbose == TRUE ){
    "Estimation of the number of patients per diagnosis."
  }
  
  if( diagnosisTime != "ALL"){
    selection <- input[ input$when == diagnosisTime, c( "patient_num", "sex", "age_group", "concept_code")]
    print( paste0( "Diagnosis counts restricted to those ", diagnosisTime ) )
  }else{
    selection <- unique( input[ , c( "patient_num", "sex", "age_group", "concept_code")] ) 
    print( "Diagnosis counts are done without considering when the diagnosis was done (before or after admission" )
    
  }
  
  
  if( by.age_group == FALSE & by.race == FALSE & by.severe == FALSE ){
    
    print( "Aggregating by sex" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex),
                                 summarise,COUNT = length(concept_code)))
  }else if( by.age_group == TRUE & by.race == FALSE & by.severe == FALSE ){
    
    print( "Aggregating by age group" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, age_group),
                                 summarise,COUNT = length(concept_code)))
  }else if( by.age_group == FALSE & by.race == TRUE & by.severe == FALSE ){
    
    print( "Aggregating by age race" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, race),
                                 summarise,COUNT = length(concept_code)))
  }else if( by.age_group == FALSE & by.race == FALSE & by.severe == TRUE ){
    
    print( "Aggregating by severe status" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, ),
                                 summarise,COUNT = length(concept_code)))
  }
  else if( by.age_group == TRUE & by.race == TRUE & by.severe == FALSE ){
    print( "Aggregating by age group and race" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, age_group, race),
                                 summarise,COUNT = length(concept_code)))
  }else if( by.age_group == TRUE & by.race == TRUE & by.severe == TRUE ){
    
    print( "Aggregating by age group, race and severe status" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, age_group, race, severe ),
                                 summarise,COUNT = length(concept_code)))
  }else if( by.age_group == TRUE & by.race == FALSE & by.severe == TRUE ){
    print( "Aggregating by age group and severe status" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, age_group, severe ),
                                 summarise,COUNT = length(concept_code)))
  }else if( by.age_group == FALSE & by.race == TRUE & by.severe == TRUE ){
    print( "Aggregating by race and severe status" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, race, severe ),
                                 summarise,COUNT = length(concept_code)))
  }else if( by.age_group == TRUE & by.race == FALSE & by.severe == TRUE ){
    print( "Aggregating by age group and severe status" )
    summary <- rbind(plyr::ddply(input,
                                 plyr::.(concept_code, sex, age_group, race, severe ),
                                 summarise,COUNT = length(concept_code)))
  }  
  
  if( verbose ==  TRUE ){
    print( "Output data.frame with diagnosis counts generated")
  }
  
  if( obfuscation != FALSE ){
    summary$COUNT <- ifelse( summary$COUNT < obfuscation, -1, summary$COUNT)
  }
  
  #output in decreasing order
  summary <- summary[ order( summary$COUNT, decreasing = TRUE), ]
  
  return( summary )
}
