#' Function to run a PheWAS analysis using Fisher
#'
#' Given the data generated by \code{phewasData} R function, perform a PheWAS analysis
#' generating as an output a \code{data.frame} with one diagnosis code per row, 
#' and the different counts, p-value, OR, CI when comparing cases vs. controls. 
#' 
#' @param input The data.frame with the sex phewas analysis. Output generated when running the \code{phewasData} R function.
#' @param age_group By default "ALL". Change it to any of the existing age_groups to focalize the analysis in a specific subset.
#' @param caco The variable that will be used as comparison. 
#' @param cases The value that will be consider as case, writen in the same way as it appears in the data. 
#' @param control The value that will be consider as control, writen in the same way as it appears in the data. 
#' @param correctionMethod The correction method for multiple testing. By default: "bonferroni"
#' @param obfuscation By default FALSE. If your IRB require obfuscation, change it to the minimum patient count allowed.
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get detailed information.
#' @return An object of class \code{data.frame} with the counts.
#' @examples
#'
#'sexFisher_all <- fisherAnalysis(
#'                    input            = dataAnalysis,
#'                    ageGroup         = "ALL",
#'                    caco             = "sex",
#'                    cases            = "female",
#'                    control          = "male",
#'                    correctionMethod = "bonferroni")
#' @export myPhewasAnalysis

fisherAnalysis <- function( input, ageGroup, caco, cases, control, correctionMethod, obfuscation = FALSE ){
  
  #age group selection
  if( ageGroup == "ALL" ){
    print( "The PheWAS will be run for all age groups together.")
  }else if( ageGroup != "ALL" ){
    print( "Selecting the age group of interest")
    print( paste0( "The PheWAS will be run in the age group ", ageGroup ) )
  }
  
  #select subset for data analysis based on the age of the patient
  if( ageGroup != "ALL"){
    subset <- unique( input[ input$age_group == ageGroup, 
                             c("patient_num", "sex", "concept_code", "age_group")] )
  }else{
    subset <- unique( input[ , c("patient_num", "sex", "concept_code" ) ])
  }
  
  
  #select the distinct diagnostic codes (3 digits level)
  phenotypes <- unique( as.character( subset$concept_code ) ) 
  subset <- as.data.frame( subset )
  
  subset$casecontrol <- as.character(ifelse( subset[caco]==cases, 1, 
                                             ifelse( subset[caco] == control, 0, NA)))
  
  
  results <- parallel::mclapply( phenotypes, tableData, mc.preschedule = TRUE, 
                                 mc.cores = 1, 
                                 data = subset,
                                 cases = 1, 
                                 control = 0 )
  
  resultsdf <- do.call("rbind", results )
  resultsdf <- as.data.frame( resultsdf, stringsAsFactors=FALSE )
  colnames(resultsdf) <- c( "Phenotype", "CasesWithPhenotye", "CasesWithoutPhenotype", 
                            "ControlsWithPhenotype", "ControlsWithoutPhenotype", 
                            "pValue", "95%confidenceInterval_min", "95%confidenceInterval_max","OddsRatio" )
  resultsdf$adjustPvalue <- p.adjust( as.numeric( resultsdf$pValue ), method = correctionMethod, n = nrow( resultsdf ) )
  
  if( obfuscation != FALSE){
    print( paste0( "Counts < ", obfuscation, " are transformed to -1") )
    resultsdf$CasesWithPhenotye <- ifelse( resultsdf$CasesWithPhenotye < obfuscation, -1, resultsdf$CasesWithPhenotye )
    resultsdf$CasesWithoutPhenotype <- ifelse( resultsdf$CasesWithoutPhenotype < obfuscation, -1, resultsdf$CasesWithoutPhenotype )
    resultsdf$ControlsWithPhenotype <- ifelse( resultsdf$ControlsWithPhenotype < obfuscation, -1, resultsdf$ControlsWithPhenotype )
    resultsdf$ControlsWithoutPhenotype <- ifelse( resultsdf$ControlsWithoutPhenotype < obfuscation, -1, resultsdf$ControlsWithoutPhenotype )
  }
  return( resultsdf)
  
}

tableData <- function ( phenoCode, data, cases, control ) {
  
  casesPresent <- length( unique ( data[ data$concept_code == phenoCode & data$casecontrol == cases, "patient_num" ] ) )
  controlPresent <-  length( unique ( data[ data$concept_code == phenoCode & data$casecontrol == control, "patient_num" ] ) )
  casesNotPresent <- length(unique( data[ data$casecontrol == cases, "patient_num"])) - casesPresent
  controlsNotPresent <- length(unique(data[ data$casecontrol == control, "patient_num"])) - controlPresent
  
  mat <- matrix( c( casesPresent, casesNotPresent, controlPresent, controlsNotPresent), ncol = 2 )
  f <- fisher.test(as.table(mat), alt="two.sided")
  c(phenoCode, casesPresent, casesNotPresent, controlPresent, controlsNotPresent, f$p.value, f$conf.int, f$estimate)
  
}
