#' Function to run a PheWAS analysis using glm
#'
#' Given the data generated by \code{phewasData} R function, perform a PheWAS analysis
#' generating as an output a \code{data.frame} with one diagnosis code per row, 
#' and the different counts, p-value, OR, CI when comparing cases vs. controls. 
#' 
#' @param input The data.frame with the sex phewas analysis. Output generated when running the \code{phewasData} R function.
#' @param age_group By default "ALL". Change it to any of the existing age_groups to focalize the analysis in a specific subset.
#' @param caco The variable that will be used as comparison. 
#' @param cases The value that will be consider as case, writen in the same way as it appears in the data. 
#' @param control The value that will be consider as control, writen in the same way as it appears in the data. 
#' @param correctionMethod The correction method for multiple testing. By default: "bonferroni"
#' @param obfuscation By default FALSE. If your IRB require obfuscation, change it to the minimum patient count allowed.
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get detailed information.
#' @return An object of class \code{data.frame} with the counts.
#' @examples
#'
#'sexPheWAS_all <- myPhewasAnalysis(
#'                    input            = dataAnalysis,
#'                    ageGroup         = "ALL",
#'                    caco             = "sex",
#'                    cases            = "female",
#'                    control          = "male",
#'                    correctionMethod = "bonferroni")
#' @export myPhewasAnalysis


myPhewasAnalysis <- function( input, ageGroup = "ALL", caco, cases, control, correctionMethod = "bonferroni", obfuscation = FALSE, verbose = FALSE ){
  
  #age group selection
  if( ageGroup == "ALL" ){
    print( "The PheWAS will be run for all age groups together.")
  }else if( ageGroup != "ALL" ){
    print( "Selecting the age group of interest")
    print( paste0( "The PheWAS will be run in the age group ", ageGroup ) )
  }
  
  #select subset for data analysis based on the age of the patient
  if( ageGroup != "ALL"){
    subset <- unique( input[ input$age_group == ageGroup, 
                            c("patient_num", "sex", "concept_code", "age_group")] )
  }else{
    subset <- unique( input[ , c("patient_num", "sex", "concept_code" ) ])
  }
  
  #select the distinct diagnostic codes (3 digits level)
  phenotypes <- unique( subset$concept_code )
  
  if( verbose == TRUE ){
    print("Generating a PheWAS matrix ...")
  }
  subset$COUNT <- 1
  phenotypedf <- as.data.frame(spread(subset, concept_code, COUNT, fill = 0))
  
  phenotypedf$casecontrol <- as.character(ifelse( phenotypedf[caco]==cases, 1, 
                                                  ifelse( phenotypedf[caco] == control, 0, NA))
  )
  
  # Logistic regression analysis #
  if( verbose == TRUE ){
    print("Running the logistic regression analysis for each diagnostic ...")
  }
  phenotypedf$casecontrol <- as.character(phenotypedf$casecontrol)
  
  phewasOutput <- as.data.frame( matrix(ncol = 7 ) )
  
  for( i in 1:length( phenotypes ) ){
    
    if( verbose == TRUE ){
      if( i %in% c(1, 10, 100, 500, 1000, 1500, 2000 )){
        print( paste0( "Diagnostic code ", i, " out of ", length( phenotypes )))
      }
    }
    
    selection <- glm( formula= phenotypedf[, as.character(phenotypes[i])]~casecontrol, family = binomial(), data=phenotypedf, na.action = na.omit)
    ci   <- exp(summary(selection)$coefficients["casecontrol1",1]+qnorm(c(0.025, 0.975)) * summary(selection)$coefficients["casecontrol1",2])
    
    colnums <- which( colnames( phenotypedf) %in% c(as.character(phenotypes[i]), "patient_num", "casecontrol"))
    if( length( colnums ) == 3 ){
      cacodf <-  phenotypedf[, c( colnums )]
      cacodf <- na.omit( cacodf )
      caseDisease <- length(unique(cacodf[ cacodf[, 2] == 1 & cacodf$casecontrol == "1", "patient_num"]))
      caseNoDisease <-  length(unique(cacodf[ cacodf[, 2] == 0 & cacodf$casecontrol == "1", "patient_num"]))
      controlDisease <-  length(unique(cacodf[ cacodf[, 2] == 1 & cacodf$casecontrol == "0", "patient_num"]))
      controlNoDisease <-  length(unique(cacodf[ cacodf[, 2] == 0 & cacodf$casecontrol == "0", "patient_num"]))
      newRow <- c ( as.character(phenotypes[i]), summary(selection)$coefficients[2], exp(summary(selection)$coefficients[2]), paste0("(", ci[1][1], ",", ci[2][1], ")"),
                    summary(selection)$coefficients[2,4], paste0(caseDisease+controlDisease,"(",caseDisease,"/",controlDisease,")"), 
                    paste0(caseNoDisease+controlNoDisease,"(",caseNoDisease,"/",controlNoDisease,")")
      )
      phewasOutput <- rbind( newRow, phewasOutput )
    }
    else if( length( colnums ) != 3 ){
      selectingVariables <- c(as.character(phenotypes[i]), "patient_num", "casecontrol")
      missing <- which(! selectingVariables %in% colnames(phenotypedf ))
      print( paste0("Variable ", selectingVariables[missing], " is missing"))
    }
  }
  
  colnames( phewasOutput ) <- c("DIAGNOSTIC", "Coefficient", "OddsRatio", "Confidence_interval", "pvalue", "Phenotype_present", "Phenotype_absent")
  phewasOutput$adjustPvalue <- p.adjust( as.numeric(phewasOutput$pvalue), method = correctionMethod)
  print("Done! Congratulations! Your PheWAS analysis has been finished!")
  return( phewasOutput)
}
